/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aha.userinterface;

import com.aha.businesslogic.model.Airport;
import com.aha.businesslogic.model.Flight;
import com.aha.businesslogic.model.User;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author HB
 */
public class ListFlightsForm extends javax.swing.JFrame {

    private User user;
    //private Flight flights;
    List<Flight> allFlights;
    private Flight selectedFlight;
    /**
     * Creates new form ListFlights
     */
    public ListFlightsForm(User user, List<Flight> flights) {
        this.user = user;
        this.allFlights = flights;
        initComponents();
        jLbl_User.setText(user.getName());
        jLbl_UserType.setText("[" + user.getClass().getSimpleName() + "]");
        listAllFlights();
        //jLabel2.setText(String.valueOf(flights.getFlightNumber()));
    }
    
    private void listAllFlights(){
        List <Flight> flights = allFlights;
        jPnl_FlightList.setLayout(new GridLayout(0, 7));
        String[] titleBar = {"Flight number", "From", "Departure", "To", "Arrival", "Price", "Book this flight"};
        for (int i = 0; i < titleBar.length; i++) {
             JLabel label = new JLabel(titleBar[i]);
             jPnl_FlightList.add(label);
        }

        ButtonGroup radioGroup = new ButtonGroup();
        
        for (Flight flight : allFlights) {
            //Flight number
            JLabel label = new JLabel(String.valueOf(flight.getFlightNumber()));
            jPnl_FlightList.add(label);
            
            //From
            label = new JLabel(String.valueOf(flight.getAirportFrom().getCode()));
            jPnl_FlightList.add(label);
            
            //Departure
            SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd-MM-yyyy h:mm a");
            String departure = DATE_FORMAT.format(flight.getDeparture());
            label = new JLabel(departure);
            jPnl_FlightList.add(label);
            
            //To
            label = new JLabel(String.valueOf(flight.getAirportTo().getCode()));
            jPnl_FlightList.add(label);
            
            //Arrival
            Calendar cal = Calendar.getInstance();
            cal.setTime(flight.getDeparture());
            
            cal.add(Calendar.MINUTE, flight.getFlightDuration());
            String arrival = DATE_FORMAT.format(cal.getTime());
            label = new JLabel(arrival);
            jPnl_FlightList.add(label);
            
            //Price
            label = new JLabel(String.valueOf(flight.getPrice()));
            jPnl_FlightList.add(label);
            
            //Radio button for booking
            JRadioButton bookFlightRadioButton = new JRadioButton();
            //Put radio button into button group
            radioGroup.add(bookFlightRadioButton);
            ActionListener flightBookingListener = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    selectedFlight = flight;
                    bookedFlightLabel.setText(String.valueOf(flight.getFlightNumber()));
                    bookFlightError.setText("");
                }
            };
            bookFlightRadioButton.addActionListener(flightBookingListener);
            jPnl_FlightList.add(bookFlightRadioButton);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_FlightNum = new javax.swing.JLabel();
        jLbl_From = new javax.swing.JLabel();
        jLbl_Departure = new javax.swing.JLabel();
        jLbl_To = new javax.swing.JLabel();
        jLbl_Arrival = new javax.swing.JLabel();
        jLbl_Price = new javax.swing.JLabel();
        jLbl_Book = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLbl_User = new javax.swing.JLabel();
        jLbl_UserType = new javax.swing.JLabel();
        jPnl_FlightList = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        bookedFlightLabel = new javax.swing.JLabel();
        bookFlightButton = new javax.swing.JButton();
        bookFlightError = new javax.swing.JLabel();

        jLbl_FlightNum.setText("Flight number");

        jLbl_From.setText("From");

        jLbl_Departure.setText("Departure");

        jLbl_To.setText("To");

        jLbl_Arrival.setText("Arrival");

        jLbl_Price.setText("Price");

        jLbl_Book.setText("Book this flight");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome");

        jLbl_User.setText("user");

        jLbl_UserType.setText("user type");

        jPnl_FlightList.setToolTipText("");
        jPnl_FlightList.setAutoscrolls(true);

        javax.swing.GroupLayout jPnl_FlightListLayout = new javax.swing.GroupLayout(jPnl_FlightList);
        jPnl_FlightList.setLayout(jPnl_FlightListLayout);
        jPnl_FlightListLayout.setHorizontalGroup(
            jPnl_FlightListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        jPnl_FlightListLayout.setVerticalGroup(
            jPnl_FlightListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        jLabel8.setText("Selected flight:");

        bookFlightButton.setText("Book flight");
        bookFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(bookedFlightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLbl_User)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbl_UserType))
                    .addComponent(jPnl_FlightList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bookFlightError)
                        .addGap(18, 18, 18)
                        .addComponent(bookFlightButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_UserType)
                    .addComponent(jLbl_User)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(bookedFlightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnl_FlightList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookFlightButton)
                    .addComponent(bookFlightError))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void bookFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightButtonActionPerformed
        // TODO add your handling code here:
        if (selectedFlight!=null) {
            SelectSeatForm selectSeatForm = new SelectSeatForm(selectedFlight, user);
            selectSeatForm.setVisible(true);
            this.dispose();
        }
        else{
            bookFlightError.setText("Please choose a flight");
            bookFlightError.setForeground(Color.red);
        }
    }//GEN-LAST:event_bookFlightButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookFlightButton;
    private javax.swing.JLabel bookFlightError;
    private javax.swing.JLabel bookedFlightLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbl_Arrival;
    private javax.swing.JLabel jLbl_Book;
    private javax.swing.JLabel jLbl_Departure;
    private javax.swing.JLabel jLbl_FlightNum;
    private javax.swing.JLabel jLbl_From;
    private javax.swing.JLabel jLbl_Price;
    private javax.swing.JLabel jLbl_To;
    private javax.swing.JLabel jLbl_User;
    private javax.swing.JLabel jLbl_UserType;
    private javax.swing.JPanel jPnl_FlightList;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
