/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aha.userinterface;

import com.aha.businesslogic.model.Airport;
import com.aha.businesslogic.model.Booking;
import com.aha.businesslogic.model.Flight;
import com.aha.businesslogic.model.Passenger;
import com.aha.data.AirportRepository;
import com.aha.data.BookingRepository;
import com.aha.data.FlightRepository;
import com.aha.data.PassengerRepository;
import java.awt.Color;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author simonicsanett
 */
public class PassengerForm extends javax.swing.JFrame {

    private Passenger passenger;

    private PassengerRepository passengerRepository = new PassengerRepository();
    private AirportRepository airportRepository = new AirportRepository();
    private FlightRepository flightRepository = new FlightRepository();
    private BookingRepository bookingRepository = new BookingRepository();

    private SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy kk:mm");

    /**
     * Creates new form PassengerForm
     */
    public PassengerForm() {
        initComponents();

        List<Airport> airports = airportRepository.getAirports();
        searchFlightsPanel.setAirports(airports);
    }

    public void setPassenger(Passenger newPassenger) {
        passenger = newPassenger;

        refresh();
    }

    private void refresh() {

        String name = passenger.getName();
        String email = passenger.getEmail();

        nameField.setText(name);
        emailField.setText(email);

        updateBookingTable();
    }

    private void updateBookingTable() {
        List<Booking> bookings = bookingRepository.getActiveBookingsByPassenger(passenger);

        DefaultTableModel bookingModel = (DefaultTableModel) bookingTable.getModel();
        bookingModel.setRowCount(0);
        for (Booking booking : bookings) {
            bookingModel.addRow(new Object[]{
                booking.getBookingReference(),
                booking.getFlight().getFlightNumber(),
                booking.getFlight().getAirportFrom(),
                booking.getFlight().getAirportTo(),
                DATE_FORMAT.format(booking.getFlight().getDeparture()),
                flightArrivalToString(booking.getFlight()),
                booking.getSeat()

            });

        }
    }

    private void listFlights(String airportCodeFrom, String airportCodeTo, Date departureFrom, Date departureTo) {
        List<Flight> flights = flightRepository.getFilteredFlights(airportCodeFrom, airportCodeTo, departureFrom, departureTo);

        DefaultTableModel listFlightModel = (DefaultTableModel) jTable1.getModel();
        listFlightModel.setRowCount(0);

        for (Flight flight : flights) {
            listFlightModel.addRow(new Object[]{
                flight.getId(),
                //Flight number
                flight.getFlightNumber(),
                //From
                flight.getAirportFrom().getCity(),
                //Departure
                DATE_FORMAT.format(flight.getDeparture()),
                //To
                flight.getAirportTo().getCity(),
                //Arrival
                flightArrivalToString(flight),
                //Price
                flight.getBasicPrice(), //Book flight
            });
        }
    }

    private String flightArrivalToString(Flight flight) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(flight.getDeparture());
        cal.add(Calendar.MINUTE, flight.getFlightDuration());
        String arrival = DATE_FORMAT.format(cal.getTime());
        return arrival;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchFlightsPanel = new com.aha.userinterface.SearchFlightsPanel();
        bookflightButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        DeleteButton = new javax.swing.JButton();
        seatChangeButton = new javax.swing.JButton();
        personalDetailsPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        savePersonalDetailsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Flight number", "From", "Departure", "To", "Arrival", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("Highlight row to select flight");
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        searchFlightsPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightsPanelActionPerformed(evt);
            }
        });

        bookflightButton.setText("Book flight");
        bookflightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookflightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchFlightsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bookflightButton)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchFlightsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(bookflightButton))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(50, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)))
        );

        jTabbedPane1.addTab("Book Flights", jPanel1);

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking Reference", "Flight Number", "From", "To", "Departure", "Arrival", "Seat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bookingTable);

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        seatChangeButton.setText("Seat change");
        seatChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatChangeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatChangeButton)
                    .addComponent(DeleteButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage Bookings", jPanel2);

        nameLabel.setText("Name:");

        emailLabel.setText("Email:");

        nameField.setSize(new java.awt.Dimension(80, 300));

        savePersonalDetailsButton.setText("Save");
        savePersonalDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePersonalDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personalDetailsPanelLayout = new javax.swing.GroupLayout(personalDetailsPanel);
        personalDetailsPanel.setLayout(personalDetailsPanelLayout);
        personalDetailsPanelLayout.setHorizontalGroup(
            personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(savePersonalDetailsButton)
                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailLabel)
                            .addComponent(nameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(561, Short.MAX_VALUE))
        );
        personalDetailsPanelLayout.setVerticalGroup(
            personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savePersonalDetailsButton)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Personal Details", personalDetailsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savePersonalDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePersonalDetailsButtonActionPerformed

        String name = nameField.getText();
        String email = emailField.getText();

        Passenger tempPassenger = new Passenger();
        tempPassenger.setName(name);
        tempPassenger.setEmail(email);
        tempPassenger.setId(passenger.getId());

        boolean result = passengerRepository.updatePassenger(tempPassenger);

        if (result) {
            passenger = tempPassenger;
        }

        refresh();

    }//GEN-LAST:event_savePersonalDetailsButtonActionPerformed

    private void searchFlightsPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightsPanelActionPerformed
        FlightSearchEvent event = (FlightSearchEvent) evt;
        listFlights(event.getAirportCodeFrom(), event.getAirportCodeTo(), event.getDepartureFrom(), event.getDepartureTo());
    }//GEN-LAST:event_searchFlightsPanelActionPerformed

    private void bookflightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookflightButtonActionPerformed
        DefaultTableModel listFlightModel = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            int flightId = (int) listFlightModel.getValueAt(row, 0);
            Flight selectedFlight = flightRepository.getFlightById(flightId);

            SelectSeatForm selectSeatForm = new SelectSeatForm(selectedFlight, passenger);
            selectSeatForm.setVisible(true);
            this.dispose();
        } //Set error msg if no flight is selected
//        else {
//            bookFlightError.setText("Please choose a flight");
//            bookFlightError.setForeground(Color.red);
//        }
    }//GEN-LAST:event_bookflightButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        DefaultTableModel bookedFlightModel = (DefaultTableModel) bookingTable.getModel();
        int row = bookingTable.getSelectedRow();
        if (row >= 0) {
            String bookingNumber = (String) bookedFlightModel.getValueAt(row, 0);
            boolean result = bookingRepository.deleteBookingByBookingreference(bookingNumber);
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete? Booking: " + bookingNumber,
                    "Deleting booking", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

            if (dialogResult == JOptionPane.OK_OPTION) {
                updateBookingTable();
            }

        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void seatChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatChangeButtonActionPerformed
        DefaultTableModel bookedFlightModel = (DefaultTableModel) bookingTable.getModel();
        int row = bookingTable.getSelectedRow();
        if (row >= 0) {
            String bookingNumber = (String) bookedFlightModel.getValueAt(row, 0);

            Booking booking = bookingRepository.getBookingByBookingReference(bookingNumber);            
            Flight flight = flightRepository.getFlightById(booking.getFlight().getId());

            SelectSeatForm changeSeat = new SelectSeatForm(flight, passenger, booking);
            changeSeat.setVisible(true);
            
            changeSeat.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    updateBookingTable();
                }
                
            });
    }//GEN-LAST:event_seatChangeButtonActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton bookflightButton;
    private javax.swing.JTable bookingTable;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel personalDetailsPanel;
    private javax.swing.JButton savePersonalDetailsButton;
    private com.aha.userinterface.SearchFlightsPanel searchFlightsPanel;
    private javax.swing.JButton seatChangeButton;
    // End of variables declaration//GEN-END:variables

}
